name: Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: Port Forward
      #   uses: enkhjile/aws-ssm-remote-port-forwarding-session-action@release/v1
      #   with:
      #     target-id: ${{ vars.TARGET_ID }}
      #     host: ${{ vars.HOST }}
      #     port: ${{ vars.PORT }}
      #     local-port: ${{ vars.LOCAL_PORT }}
      - name: Port Forward
        run: |
          aws ssm start-session --target ${{ vars.TARGET_ID }} --document-name AWS-StartPortForwardingSessionToRemoteHost --parameters host=${{ vars.HOST }},portNumber=${{ vars.PORT }},localPortNumber=${{ vars.LOCAL_PORT }} &
      - name: List port forward
        run: |
          netstat -tuln
      - name: Ping postgres
        run: |
          psql -h localhost -p ${{ vars.LOCAL_PORT }} -U ${{ vars.USER }} -d ${{ vars.DB }} -c "SELECT 1"

